### ISSUE TITLE
[Feature #1]: As a user i want to be able to login

### ISSUE THREAD

**Issue by TjerkZ** [TjerkZ/S3-Dreamcatcher#1]
## Discription
make a login sytem with auth0

## Tasks

- [ ] make auth0 account
- [ ] create react project
- [ ] implement auth0 with react
- [ ] create c# backend project
- [ ] implement authenication with frontend
- [ ] setup CICD to docker hub
- [ ] host containers from dockerhub on server
